[workspace]
resolver = "2"
members = ["packet"]

[patch.crates-io]
log = { git = "https://github.com/rust-lang/log.git" }
quickcheck = { git = "https://github.com/burntsushi/quickcheck.git" }
quickcheck_macros = { git = "https://github.com/burntsushi/quickcheck.git" }
strum = { git = "https://github.com/peternator7/strum.git" }
strum_macros = { git = "https://github.com/peternator7/strum.git" }
