#[repr(u8)]
#[derive(Clone, Copy, Debug, Hash, Eq, Ord, PartialEq, PartialOrd)]
pub enum Instruction {
    Ping = 0x01,
    Read = 0x02,
    Write = 0x03,
    RegWrite = 0x04,
    Action = 0x05,
    FactoryReset = 0x06,
    Reboot = 0x08,
    Clear = 0x10,
    ControlTableBackup = 0x20,
    Status = 0x55,
    SyncRead = 0x82,
    SyncWrite = 0x83,
    FastSyncRead = 0x8A,
    BulkRead = 0x92,
    BulkWrite = 0x93,
    FastBulkRead = 0x9A,
}

#[repr(u8)]
#[derive(Clone, Copy, Debug, Hash, Eq, Ord, PartialEq, PartialOrd)]
pub enum ControlTable {
    ModelNumber = 0,
    ModelInformation = 2,
    FirmwareVersion = 6,
    Id = 7,
    BaudRate = 8,
    ReturnDelayTime = 9,
    DriveMode = 10,
    OperatingMode = 11,
    SecondaryId = 12,
    ProtocolType = 13,
    HomingOffset = 20,
    MovingThreshold = 24,
    TemperatureLimit = 31,
    MaxVoltageLimit = 32,
    MinVoltageLimit = 34,
    PwmLimit = 36,
    CurrentLimit = 38,
    VelocityLimit = 44,
    MaxPositionLimit = 48,
    MinPositionLimit = 52,
    StartupConfiguration = 60,
    PwmSlope = 62,
    Shutdown = 63,
    TorqueEnable = 64,
    Led = 65,
    StatusReturnLevel = 68,
    RegisteredInstruction = 69,
    HardwareErrorStatus = 70,
    VelocityIGain = 76,
    VelocityPGain = 78,
    PositionDGain = 80,
    PositionIGain = 82,
    PositionPGain = 84,
    Feedforward2ndGain = 88,
    Feedforward1stGain = 90,
    BusWatchdog = 98,
    GoalPwm = 100,
    GoalCurrent = 102,
    GoalVelocity = 104,
    ProfileAcceleration = 108,
    ProfileVelocity = 112,
    GoalPosition = 116,
    RealtimeTick = 120,
    Moving = 122,
    MovingStatus = 123,
    PresentPwm = 124,
    PresentCurrent = 126,
    PresentVelocity = 128,
    PresentPosition = 132,
    VelocityTrajectory = 136,
    PositionTrajectory = 140,
    PresentInputVoltage = 144,
    PresentTemperature = 146,
    BackupReady = 147,
}

impl ControlTable {
    #[inline]
    pub const fn bytes(&self) -> u8 {
        match *self {
            Self::ModelNumber => 2,
            Self::ModelInformation => 4,
            Self::FirmwareVersion => 1,
            Self::Id => 1,
            Self::BaudRate => 1,
            Self::ReturnDelayTime => 1,
            Self::DriveMode => 1,
            Self::OperatingMode => 1,
            Self::SecondaryId => 1,
            Self::ProtocolType => 1,
            Self::HomingOffset => 4,
            Self::MovingThreshold => 4,
            Self::TemperatureLimit => 1,
            Self::MaxVoltageLimit => 2,
            Self::MinVoltageLimit => 2,
            Self::PwmLimit => 2,
            Self::CurrentLimit => 2,
            Self::VelocityLimit => 4,
            Self::MaxPositionLimit => 4,
            Self::MinPositionLimit => 4,
            Self::StartupConfiguration => 1,
            Self::PwmSlope => 1,
            Self::Shutdown => 1,
            Self::TorqueEnable => 1,
            Self::Led => 1,
            Self::StatusReturnLevel => 1,
            Self::RegisteredInstruction => 1,
            Self::HardwareErrorStatus => 1,
            Self::VelocityIGain => 2,
            Self::VelocityPGain => 2,
            Self::PositionDGain => 2,
            Self::PositionIGain => 2,
            Self::PositionPGain => 2,
            Self::Feedforward2ndGain => 2,
            Self::Feedforward1stGain => 2,
            Self::BusWatchdog => 1,
            Self::GoalPwm => 2,
            Self::GoalCurrent => 2,
            Self::GoalVelocity => 4,
            Self::ProfileAcceleration => 4,
            Self::ProfileVelocity => 4,
            Self::GoalPosition => 4,
            Self::RealtimeTick => 2,
            Self::Moving => 1,
            Self::MovingStatus => 1,
            Self::PresentPwm => 2,
            Self::PresentCurrent => 2,
            Self::PresentVelocity => 4,
            Self::PresentPosition => 4,
            Self::VelocityTrajectory => 4,
            Self::PositionTrajectory => 4,
            Self::PresentInputVoltage => 2,
            Self::PresentTemperature => 1,
            Self::BackupReady => 1,
        }
    }
}
