[package]
name = "picomixel"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
cortex-m-rt = { git = "https://github.com/rust-embedded/cortex-m.git" }
cyw43 = { git = "https://github.com/embassy-rs/embassy.git", features = [
  "bluetooth",
  "defmt",
  "firmware-logs",
] }
cyw43-pio = { git = "https://github.com/embassy-rs/embassy.git", features = [
  "defmt",
] }
defmt = { git = "https://github.com/knurling-rs/defmt.git" }
defmt-rtt = { git = "https://github.com/knurling-rs/defmt.git" }
# dxl-driver = { path = "../driver" }
dxl-rp = { path = "../rp" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", features = [
  "arch-cortex-m",
  "defmt",
  "executor-interrupt",
  "executor-thread",
  "nightly",
] }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", features = [
  "defmt",
  "defmt-timestamp-uptime",
] }
embassy-rp = { git = "https://github.com/embassy-rs/embassy.git", features = [
  "binary-info",
  "critical-section-impl",
  "defmt",
  "rp235xa",
  "time-driver",
  "unstable-pac",
] }
panic-probe = { git = "https://github.com/knurling-rs/defmt.git", features = [
  "print-defmt",
] }
static_cell = { git = "https://github.com/embassy-rs/static-cell.git" }

[build-dependencies]
reqwest = { git = "https://github.com/seanmonstar/reqwest.git", features = [
  "blocking",
] }
