[target.'cfg(all(target_arch = "arm", target_os = "none"))']
linker = "flip-link"
# runner = "picotool load -u -v -x -t elf"
runner = "probe-rs run --chip RP235x"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
RUST_BACKTRACE = "1"
